"""ReportGenerator: turn a DataCollector's JSON into a markdown report.

Solver-agnostic. Renders:
  - case header (case_id, executor mode, verdict level)
  - the four-question gate answers
  - the gold comparison table
  - the residual convergence table
  - the physics pre-flight result
  - the correction suggestions (if any)

Stage 1+2: pure markdown, no plots. Stage 3+ may add PNG plots via
`cfd_harness.starccm_adapter.visualize` (deferred).
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict

from jinja2 import Environment, BaseLoader, select_autoescape

__all__ = ["ReportGenerator"]


def _fmt_num(v: Any) -> str:
    """Format a measured/gold value; em-dash for None/nan/inf/non-numeric."""
    if v is None:
        return "—"
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    if f != f or f in (float("inf"), float("-inf")):
        return "—"
    return f"{f:.4g}"


def _fmt_pct(v: Any) -> str:
    """Format a fractional error/tolerance as a percentage; em-dash otherwise."""
    if v is None:
        return "—"
    try:
        f = float(v)
    except (TypeError, ValueError):
        return "—"
    if f != f or f in (float("inf"), float("-inf")):
        return "—"
    return f"{f * 100:.2f}%"


_REPORT_TEMPLATE = """# {{ case_id }} · V&V Report

> Generated by `cfd-harness-windows-starccm` v{{ spec_version }}
> on {{ generated_at }} (UTC).
> Executor mode: **{{ executor_mode }}** {% if is_mock %}(MOCK — verdict ceiling WARN){% endif %}

## Verdict

**Level**: `{{ level }}`
**Validation status**: {% if is_validated %}✅ validated{% else %}❌ not validated{% endif %}
**Comparison**: {% if comparison_all_pass %}✅ all quantities within tolerance{% else %}❌ {{ comparison_failing | join(', ') }} outside tolerance{% endif %}
**Convergence**: {% if convergence_all_pass %}✅ all residuals below floor{% else %}❌ {{ convergence_failing | join(', ') }} above floor{% endif %}
**Physics pre-flight**: {% if physics_all_pass %}✅{% else %}❌ {{ physics_failures | join('; ') }}{% endif %}

## Executor

- Mode: `{{ executor_mode }}`
- Contract hash: `{{ contract_hash }}`
- Spec version: `{{ spec_version }}`
- Notes: {{ notes | join(' · ') }}

## Measured vs Gold

| Quantity | Measured | Gold | Relative error | Tolerance | Pass |
|---|---|---|---|---|---|
{% for q in quantities -%}
| `{{ q.name }}` | {{ q.measured }} | {{ q.gold }} | {{ q.relative_error_pct }} | {{ q.tolerance_pct }} | {{ "✅" if q.all_pass else "❌" }} |
{% endfor %}

## Residuals

| Field | Final value | Floor |
|---|---|---|
{% for r in residuals -%}
| `{{ r.field }}` | {{ r.value }} | {{ r.floor }} |
{% endfor %}

{% if suggestions -%}
## Suggestions

{% for s in suggestions -%}
- **[{{ s.severity }}]** {{ s.category }}: {{ s.message }}
{% endfor %}
{% endif -%}

---
_Signed at `{{ contract_hash[:12] }}...`._
"""


class ReportGenerator:
    """Render a data.json (from DataCollector) into a markdown report."""
    def __init__(self) -> None:
        self._env = Environment(
            loader=BaseLoader(),
            autoescape=select_autoescape(disabled_extensions=("md",), default=False),
        )

    def render(self, data_path: Path) -> str:
        """Render a markdown report from a DataCollector data.json file."""
        payload = json.loads(data_path.read_text(encoding="utf-8"))
        return self._render_payload(payload)

    def _render_payload(self, payload: Dict[str, Any]) -> str:
        # Flatten for jinja
        task = payload["task_spec"]
        run = payload["run_report"]
        ver = payload["verifier_report"]

        # Per-quantity table rows. Prefer the full per-quantity detail the
        # comparator computes (measured / gold / relative-error); fall back
        # to failing-quantity names only for older data.json that predates
        # the comparison_quantities field.
        quantities = []
        for q in ver.get("comparison_quantities", []) or []:
            quantities.append({
                "name": q.get("name", "?"),
                "measured": _fmt_num(q.get("measured")),
                "gold": _fmt_num(q.get("gold")),
                "relative_error_pct": _fmt_pct(q.get("relative_error")),
                "tolerance_pct": _fmt_pct(q.get("tolerance")),
                "all_pass": bool(q.get("all_pass", False)),
            })
        if not quantities:
            for q in ver.get("comparison_failing", []) or []:
                quantities.append({
                    "name": q, "measured": "—", "gold": "—",
                    "relative_error_pct": "—", "tolerance_pct": "—",
                    "all_pass": False,
                })

        residuals = [
            {"field": k, "value": v, "floor": "1e-4"}
            for k, v in (run.get("execution_result") or {}).get("residuals", {}).items()
        ]
        if not residuals:
            residuals = [{"field": "—", "value": "—", "floor": "—"}]

        notes = run.get("notes", [])
        if not notes:
            notes = ["(none)"]

        context = {
            "case_id": task["case_id"],
            "executor_mode": run["mode"],
            "is_mock": (run.get("execution_result") or {}).get("is_mock", False),
            "level": ver["level"],
            "is_validated": ver.get("is_validated", False),
            "comparison_all_pass": ver.get("comparison_all_pass", False),
            "comparison_failing": ver.get("comparison_failing", []),
            "convergence_all_pass": ver.get("convergence_all_pass", False),
            "convergence_failing": ver.get("convergence_failing", []),
            "physics_all_pass": ver.get("physics_all_pass", False),
            "physics_failures": ver.get("physics_failures", []),
            "contract_hash": run.get("contract_hash", ""),
            "spec_version": run.get("version", ""),
            "notes": notes,
            "quantities": quantities,
            "residuals": residuals,
            "suggestions": ver.get("suggestions", []),
            "generated_at": datetime.utcnow().isoformat() + "Z",
        }
        return self._env.from_string(_REPORT_TEMPLATE).render(**context)
